##
## ZCRankup by Xx_EvilMelon_xX <3
##

commands-prefix: "&3&l{ ZCRankup }"
no-permissions: "&4No tienes permisos para ejecutar este comando!"
no-rankup-available: "&4No tienes ningun rango disponible para subir"
maximum-rank: "&4Ya tienes el rango máximo"
requisites-not-meet: "&4No cumples con los requisitos para hacer rankup"
