name: zelthicraft-rankup
version: '${version}'
main: dev.spozap.zelthicraftrankup.Main
api-version: '1.20'
depend:
  - LuckPerms
commands:
  rangos:
    usage: /rangos
    description: Muestra un menú con los rangos disponibles para rankup
