name: zelthicraft-rankup
version: '${version}'
main: dev.spozap.zelthicraftrankup.Main
api-version: '1.20'
depend:
  - Vault
commands:
  rangos:
    usage: /rangos
    description: Muestra un menú con los rangos disponibles para rankup
  rankup:
    usage: /rankup <rango>
    description: Subir al siguiente rango
