name: zelthicraft-rankup
version: '${version}'
main: dev.spozap.zelthicraftrankup.ZCRankup
api-version: '1.20'
depend:
  - Vault
commands:
  rangos:
    usage: /rangos
    description: Muestra un menú con los rangos disponibles para rankup
  rankup:
    usage: /rankup <rango>
    description: Subir al siguiente rango
  tiempojugado:
    usage: /tiempojugado
    description: Muestra el tiempo jugado
  zcreload:
    usage: /zcreload
    description: Recarga el plugin
